api:
  dashboard: true
  insecure: false
deployment:
  enabled: true
  podAnnotations: {}
  podLabels: {}
  replicas: 1
env:
- name: GOMEMLIMIT
  value: 1300MiB
- name: GOGC
  value: "75"
logs:
  access:
    enabled: true
    format: common
  general:
    format: common
    level: INFO
ports:
  web:
    expose:
      default: true
    exposedPort: 80
    port: 80
    protocol: TCP
  websecure:
    expose:
      default: true
    exposedPort: 443
    port: 443
    protocol: TCP
providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowEmptyServices: false
    allowExternalNameServices: true
    enabled: true
  kubernetesIngress:
    allowEmptyServices: false
    allowExternalNameServices: true
    enabled: true
resources:
  limits:
    cpu: 1500m
    memory: 1536Mi
  requests:
    cpu: 300m
    memory: 384Mi
service:
  annotations: {}
  enabled: true
  labels: {}
  spec: {}
  type: LoadBalancer
