# ============================================================
# Gitea Runner Token Secret - gitea-advacts
# ============================================================
# 组织级 Runner 注册 Token
# ============================================================

apiVersion: v1
kind: Secret
metadata:
  name: gitea-org-runner-token
  namespace: gitea-advacts
  labels:
    app: gitea-runner-dind
type: Opaque
data:
  # Token: 2qsfG21yaoJHUPG1E8JoikRiNJXhVrrbKKGzFMzJ
  token: MnFzZkcyMXlhb0pIVVBHMUU4Sm9pa1JpTkpYaFZycmJLS0d6Rk16Sgo=
