apiVersion: v1
data:
  tls.crt: <base64-encoded-certificate>
  tls.key: <REDACTED>
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"tls.crt":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQVdPZ0F3SUJBZ0lVY2orRERwcFNyUWc0UEhmYlhTYUI0aGNudzB3d0NnWUlLb1pJemowRUF3SXcKTERFT01Bd0dBMVVFQ2d3RlUwbFRXVk14R2pBWUJnTlZCQU1NRVZOSlUxbFRJRWx1ZEdWeWJtRnNJRU5CTUI0WApEVEkyTURRd056QTRNekF5TkZvWERUTTJNRFF3TkRBNE16QXlORm93TERFT01Bd0dBMVVFQ2d3RlUwbFRXVk14CkdqQVlCZ05WQkFNTUVWTkpVMWxUSUVsdWRHVnlibUZzSUVOQk1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVRQmoyeVVrSmlNaVZoMERjQW5VKzBaeFpnUXRCS1ZMeSt6bXJ5dXd4N2tpejE5d2NpeXpSV2sxLwp0NVZKQnBEL1JQeHNoaWorb1dwVlV6SmtkUkhDbEtOak1HRXdIUVlEVlIwT0JCWUVGRVJ0UjVmdFEvV3pCcitzCk1aV0x5a2NSUFJoMk1COEdBMVVkSXdRWU1CYUFGRVJ0UjVmdFEvV3pCcitzTVpXTHlrY1JQUmgyTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0VHTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUdEdAptcWtIeXhwTEhCQ0VMd2I3TndjVVFJK3QvNVFVWGFkYzBva3I5YnhNQWlCRTVNT0l1MjN3Q1NxVVQ3Y0QxSnZBCjlNdzNQb1JUbnpmL2ZtdzhCeDNNd0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","tls.key":"LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1waHF1UTlGWDJTNmdCT01UMGE5N2tpaG80b3VUa21pNjVvVDdwWm85QUxvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUUJqMnlVa0ppTWlWaDBEY0FuVSswWnhaZ1F0QktWTHkrem1yeXV3eDdraXoxOXdjaXl6UgpXazEvdDVWSkJwRC9SUHhzaGlqK29XcFZVekprZFJIQ2xBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo="},"kind":"Secret","metadata":{"annotations":{},"name":"sisys-internal-ca","namespace":"cert-manager"},"type":"kubernetes.io/tls"}

      '
  creationTimestamp: '2026-04-07T08:30:45Z'
  name: sisys-internal-ca
  namespace: cert-manager
  resourceVersion: '2845089'
  uid: 0f1eaac9-0b28-4719-a1c8-b474361a4204
type: kubernetes.io/tls
