"""pyahocorasick 类型存根"""

from __future__ import annotations

from typing import Any

class Automaton:
    """AC 自动机"""

    def __init__(self) -> None: ...
    def add_word(self, key: str, value: Any) -> None: ...
    def make_automaton(self) -> None: ...
    def iter(self, string: str) -> Any: ...
    def get(self, key: str) -> Any: ...
    def exists(self, key: str) -> bool: ...
    def __contains__(self, key: str) -> bool: ...
